import { Inter } from "next/font/google";
import "./globals.css";
import connectDB from "@/lib/config";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  try {
    await connectDB();
    console.log("Connected to database");
  } catch (error) {
    console.log("Error while connecting to the database:", error);
  }

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
